<RememberSequenceSequenceWidget>:
    font_size: isp(40)
    bold: True
    size_hint: (1., 1.)
    pos_hint: {"top":1}
    halign: 'center'
    valign: 'middle'
    text_size: self.size

<RememberSequenceHintWidget>:
    font_size: isp(20)
    bold: True
    halign: 'center'
    text: "NOT IMPLEMENTED"
    text_size: self.size
    valign: 'middle'

<RememberSequenceDescriptionWidget>:
    orientation: 'vertical'
    padding: (0,0,0,dp(30))
    text_after_hide: "NOT IMPLEMENTED"
